version: '3.8'

services:
  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: lms_db
      POSTGRES_USER: lms_user
      POSTGRES_PASSWORD: lms_password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5434:5432"

  web:
    build: .
    command: >
      sh -c "python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/app
    ports:
      - "8002:8000"
    depends_on:
      - db
    environment:
      - DB_NAME=lms_db
      - DB_USER=lms_user
      - DB_PASSWORD=lms_password
      - DB_HOST=db
      - DB_PORT=5432

volumes:
  postgres_data: